name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    steps:
      uses: cloudflare/wrangler-action@2.0.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}